entrypoint: "gunicorn -b :$PORT app:app --timeout 500"
runtime: python
env: flex
service: tweet-hate-speech-checker
runtime_config:
  python_version: 3.8
instance_class: B1
manual_scaling:
  instances: 1
liveness_check:
  path: "/liveness_check"
